server:
  port: 8080
  servlet:
    context-path: /api

spring:
    datasource:
      url: jdbc:h2:mem:series-db
      driverClassName: org.h2.Driver
      username: root
      password: root
    jpa:
      database-plataform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create
    h2:
      console:
        enabled: true
        path: /h2-console

logging:
  level:
    root: info
  file:
    path: ./logs/speciality-app.log