/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.camilo.teste.gradle.first;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
