version: "3.7"
services:
  application:
    container_name: drone_feeder_app
    build: .
    restart: always
    ports:
      - 8888:8888
    links:
      - mysql
  mysql:
    image: mysql:8.0.29
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drone_feeder
